name: Run Integration Tests

on: [pull_request]

jobs:
  run_behave_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install --upgrade pipenv
        pipenv install --three --dev --ignore-pipfile
    - name: Create environment file
      shell: bash
      env:
        ENVIRONMENT_FILE: ${{ secrets.NP_INTEGRATION_TEST_ENV }}
      run: |
        echo "$ENVIRONMENT_FILE" > ./features/example.py
    - name: Run Behave Tests
      run: |
        pipenv run behave
